### ISSUE TITLE
Uncaught exception when running for the first time without a .env file

### ISSUE THREAD

**Issue by nicobrenner** [nicobrenner/commandjobs#10]
```
Traceback (most recent call last):
  File "/repo/src/menu.py", line 354, in <module>
    curses.wrapper(main)
  File "/usr/local/lib/python3.9/curses/__init__.py", line 94, in wrapper
    return func(stdscr, *args, **kwds)
  File "/repo/src/menu.py", line 350, in main
    app = MenuApp(stdscr, logger)
  File "/repo/src/menu.py", line 25, in __init__
    self.db_manager = DatabaseManager(self.db_path)  # Specify the path
  File "/repo/src/database_manager.py", line 6, in __init__
    self.conn = sqlite3.connect(db_path)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

**Comment by nicobrenner** [comment]
It should be fixed with PR https://github.com/nicobrenner/commandjobs/pull/11

Closing
